title: 'awebsome.realestate::lang.plugin.name'
modelClass: Awebsome\Realestate\Models\Realty
list: $/awebsome/realestate/models/realty/columns.yaml
recordUrl: 'awebsome/realestate/realties/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'

recordsPerPage: '15'
showSetup: true
showCheckboxes: true

defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'

filter: config_filter.yaml
