# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    category:
        label: awebsome.realestate::lang.realty.category
        modelClass: Awebsome\Realestate\Models\Category
        nameFrom: title
        conditions: category_id in (:filtered)

    created_date:
        label: awebsome.realestate::lang.realty.create_at
        type: daterange
        conditions: created_at >= ':after' AND created_at <= ':before'

    updated_date:
        label: awebsome.realestate::lang.realty.update_at
        type: daterange
        conditions: updated_at >= ':after' AND updated_at <= ':before'

    parent:
        label: awebsome.realestate::lang.realty.published
        type: switch
        conditions:
             - published <> 1
             - published <> 0