name: Realties
modelClass: Awebsome\Realestate\Models\Realty
form: $/awebsome/realestate/models/realty/fields.yaml
defaultRedirect: awebsome/realestate/realties
create:
    redirect: 'awebsome/realestate/realties/update/:id'
    redirectClose: awebsome/realestate/realties
update:
    redirect: awebsome/realestate/realties
    redirectClose: awebsome/realestate/realties
preview: {  }
