# ===================================
#  Relation Behavior Config
# ===================================

properties:
    label: awebsome.realestate::lang.realty.properties
    list: ~/plugins/awebsome/realestate/models/property/columns.yaml
    form: ~/plugins/awebsome/realestate/models/property/fields.yaml
    emptyMessage: backend::lang.list.no_records
