name: Categories
modelClass: Awebsome\Realestate\Models\Category
form: $/awebsome/realestate/models/category/fields.yaml
defaultRedirect: awebsome/realestate/categories
create:
    redirect: 'awebsome/realestate/categories/update/:id'
    redirectClose: awebsome/realestate/categories
update:
    redirect: awebsome/realestate/categories
    redirectClose: awebsome/realestate/categories
preview: {  }
