title: Categories
modelClass: Awebsome\Realestate\Models\Category
list: $/awebsome/realestate/models/category/columns.yaml
recordUrl: 'awebsome/realestate/categories/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
