# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Property

# Model Form Field configuration
form: $/awebsome/realestate/models/property/fields.yaml

# Model Class name
modelClass: Awebsome\Realestate\Models\Property

# Default redirect location
defaultRedirect: awebsome/realestate/properties

# Create page
create:
    title: Create Property
    redirect: awebsome/realestate/properties/update/:id
    redirectClose: awebsome/realestate/properties

# Update page
update:
    title: Edit Property
    redirect: awebsome/realestate/properties
    redirectClose: awebsome/realestate/properties

# Preview page
preview:
    title: Preview Property
