plugin:
    name: 'awebsome.realestate::lang.plugin.name'
    description: 'awebsome.realestate::lang.plugin.description'
    author: awebsome
    icon: oc-icon-building
    homepage: ''
permissions:
    awebsome.realestate.access.realty:
        tab: 'awebsome.realestate::lang.plugin.name'
        label: 'awebsome.realestate::lang.plugin.name'
navigation:
    estate:
        label: 'awebsome.realestate::lang.plugin.name'
        url: awebsome/realestate/realties
        icon: icon-building
        permissions:
            - awebsome.realestate.access.realty
        sideMenu:
            realty:
                label: 'awebsome.realestate::lang.plugin.name'
                url: awebsome/realestate/realties
                icon: icon-building-o
                permissions:
                    - awebsome.realestate.access.realty
            category:
                label: 'awebsome.realestate::lang.plugin.category'
                url: awebsome/realestate/categories
                icon: icon-folder
                permissions:
                    - awebsome.realestate.access.realty
            tags:
                label: 'awebsome.realestate::lang.tags.title'
                url: awebsome/realestate/tags
                icon: icon-tags
                permissions:
                    - awebsome.realestate.access.realty
