# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Message

# Model Form Field configuration
form: $/awebsome/realestate/models/message/fields.yaml

# Model Class name
modelClass: Awebsome\Realestate\Models\Message

# Default redirect location
defaultRedirect: awebsome/realestate/messages

# Create page
create:
    title: Create Message
    redirect: awebsome/realestate/messages/update/:id
    redirectClose: awebsome/realestate/messages

# Update page
update:
    title: Edit Message
    redirect: awebsome/realestate/messages
    redirectClose: awebsome/realestate/messages

# Preview page
preview:
    title: Preview Message
