name: Features
modelClass: Awebsome\Realestate\Models\Feature
form: $/awebsome/realestate/models/feature/fields.yaml
defaultRedirect: awebsome/realestate/features
create:
    redirect: 'awebsome/realestate/features/update/:id'
    redirectClose: awebsome/realestate/features
update:
    redirect: awebsome/realestate/features
    redirectClose: awebsome/realestate/features
preview: {  }
